server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(cj+Z3A1WJueCXlmHz0tjGCUSNZgE9SRdJpDIVfO99r2qp2XVxpcSMA1cUnvFWevdmLw9voJq8Qy5BAaDk3N2HXvusuo7DPI4avrbEhRSttk=)
    username: ENC(Tyam9b6RUuYSrXnvMamaag==)
    password: ENC(oZmAh2nrvzoBoR6tX2CePjxm0fdjKDha)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_batch_fetch_size: 500
    database: mysql
  data:
    redis:
      host: localhost
      port: 6379
      password: aaaa
  springdoc:
    swagger-ui:
      tags-sorter: method
      display-request-duration: true
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true
    default-consumes-media-type: application/json;charset=UTF-8

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

config:
  url:
#    fe: ENC(W4HaYgATG1KYJ+rTsr1J9jjwg6Non+Tgx/d7cKSzTSQ=)
    fe: ENC(b1C10q1oU3kyLLl3yejsh5k1D3/gMKpVy+jKpdmfsqPGqmfW0CvitA==)

cloud:
  aws:
    credentials:
      accessKey: ENC(ajVyeumJjqDNWZeLKrw8vz/Gjupnb7Xmfs2c8ApgkDo=)
      secretKey: ENC(4NtM/RNyIv/ss9uRHJtrlwMPNT5MXcuDBZkXqTXIAnBqE2TZhqhNkcr04rxmTrZhOdGraDG3oDE=)
    region:
      static: ap-northeast-2
    s3:
      bucket: hanaro-meteor
    stack:
      auto: false
apikey:
  ocrurl: ENC(Igc2XEdkgbhm4z4tmVglnRyOUuD+jXDnvTux9feT3C3W8lAYh5rm2JFg5xXYowJuSBpQ7F4HYryHcGHzOFF8k3iZsglTR4gGdiS36mkTKDCrQdxZlALYZPyrmmfT+l9exiQ7UPqrJsn71R6nqLYcr4v6ih54cQ6up3et0vfn/NHg6oGThQZA0A==)
  ocrkey: ENC(/E0Q+vjUWFzylRPl9dYBiA6eQUzUiDUu4AoHtAXoxtWtuwAW1Z1DAdFMlooMf0dvfZx33pOXZfU=)

pdf:
  secret: ENC(BeUyKaFB41Y/guevRssqkTAGa6itVWV8tRSg18C0VCs=)